-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.5.0.102
-- Module  Version: 5.8
--/d/jspc29/lattice/diamond/3.5_x64/ispfpga/bin/lin64/scuba -w -n ddr_20 -lang vhdl -synth synplify -bus_exp 7 -bb -arch ep5c00 -type iol -mode out -io_type LVDS25 -width 20 -freq_in 480 -gear 2 -clk eclk -aligned -num_clk 2 

-- Fri Jul  3 11:01:17 2015

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp3;
use ecp3.components.all;
-- synopsys translate_on

entity ddr_20 is
    port (
        clk: in  std_logic; 
        clkout: out  std_logic; 
        pll_lock: out  std_logic; 
        pll_reset: in  std_logic; 
        reset: in  std_logic; 
        sclk: out  std_logic; 
        da0: in  std_logic_vector(19 downto 0); 
        da1: in  std_logic_vector(19 downto 0); 
        db0: in  std_logic_vector(19 downto 0); 
        db1: in  std_logic_vector(19 downto 0); 
        q: out  std_logic_vector(19 downto 0));
end ddr_20;

architecture Structure of ddr_20 is

    -- internal signal declarations
    signal buf_clkout: std_logic;
    signal dqclk14: std_logic;
    signal dqclk04: std_logic;
    signal dqclk13: std_logic;
    signal dqclk03: std_logic;
    signal dqclk12: std_logic;
    signal dqclk02: std_logic;
    signal dqclk11: std_logic;
    signal dqclk01: std_logic;
    signal dqclk10: std_logic;
    signal dqclk00: std_logic;
    signal cdiv8: std_logic;
    signal cdiv4: std_logic;
    signal cdiv1: std_logic;
    signal scuba_vhi: std_logic;
    signal eclk: std_logic;
    signal reset_d2: std_logic;
    signal reset_d1: std_logic;
    signal clkok2: std_logic;
    signal clkok: std_logic;
    signal clkos: std_logic;
    signal clkop: std_logic;
    signal scuba_vlo: std_logic;
    signal clkintfb: std_logic;
    signal buf_qo19: std_logic;
    signal buf_qo18: std_logic;
    signal buf_qo17: std_logic;
    signal buf_qo16: std_logic;
    signal buf_qo15: std_logic;
    signal buf_qo14: std_logic;
    signal buf_qo13: std_logic;
    signal buf_qo12: std_logic;
    signal buf_qo11: std_logic;
    signal buf_qo10: std_logic;
    signal buf_qo9: std_logic;
    signal buf_qo8: std_logic;
    signal buf_qo7: std_logic;
    signal buf_qo6: std_logic;
    signal buf_qo5: std_logic;
    signal buf_qo4: std_logic;
    signal buf_qo3: std_logic;
    signal buf_qo2: std_logic;
    signal buf_qo1: std_logic;
    signal buf_qo0: std_logic;
    signal sclk_t: std_logic;

    -- local component declarations
    component EHXPLLF
        generic (FEEDBK_PATH : in String; CLKOK_INPUT : in String; 
                DELAY_PWD : in String; DELAY_VAL : in Integer; 
                CLKOS_TRIM_DELAY : in Integer; 
                CLKOS_TRIM_POL : in String; 
                CLKOP_TRIM_DELAY : in Integer; 
                CLKOP_TRIM_POL : in String; CLKOK_BYPASS : in String; 
                CLKOS_BYPASS : in String; CLKOP_BYPASS : in String; 
                PHASE_DELAY_CNTL : in String; DUTY : in Integer; 
                PHASEADJ : in String; CLKOK_DIV : in Integer; 
                CLKOP_DIV : in Integer; CLKFB_DIV : in Integer; 
                CLKI_DIV : in Integer; FIN : in String);
        port (CLKI: in  std_logic; CLKFB: in  std_logic; 
            RST: in  std_logic; RSTK: in  std_logic; 
            WRDEL: in  std_logic; DRPAI3: in  std_logic; 
            DRPAI2: in  std_logic; DRPAI1: in  std_logic; 
            DRPAI0: in  std_logic; DFPAI3: in  std_logic; 
            DFPAI2: in  std_logic; DFPAI1: in  std_logic; 
            DFPAI0: in  std_logic; FDA3: in  std_logic; 
            FDA2: in  std_logic; FDA1: in  std_logic; 
            FDA0: in  std_logic; CLKOP: out  std_logic; 
            CLKOS: out  std_logic; CLKOK: out  std_logic; 
            CLKOK2: out  std_logic; LOCK: out  std_logic; 
            CLKINTFB: out  std_logic);
    end component;
    component FD1S3BX
        port (D: in  std_logic; CK: in  std_logic; PD: in  std_logic; 
            Q: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component OB
        port (I: in  std_logic; O: out  std_logic);
    end component;
    component CLKDIVB
        port (CLKI: in  std_logic; RST: in  std_logic; 
            RELEASE: in  std_logic; CDIV1: out  std_logic; 
            CDIV2: out  std_logic; CDIV4: out  std_logic; 
            CDIV8: out  std_logic);
    end component;
    component ODDRX2D
        generic (MEMMODE : in String; ISI_CAL : in String);
        port (DA0: in  std_logic; DB0: in  std_logic; DA1: in  std_logic; 
            DB1: in  std_logic; SCLK: in  std_logic; 
            DQCLK1: in  std_logic; DQCLK0: in  std_logic; 
            Q: out  std_logic);
    end component;
    component DQSBUFE1
        generic (DYNDEL_CNTL : in String; DYNDEL_VAL : in Integer; 
                DYNDEL_TYPE : in String);
        port (ECLKW: in  std_logic; RST: in  std_logic; 
            DYNDELPOL: in  std_logic; DYNDELAY6: in  std_logic; 
            DYNDELAY5: in  std_logic; DYNDELAY4: in  std_logic; 
            DYNDELAY3: in  std_logic; DYNDELAY2: in  std_logic; 
            DYNDELAY1: in  std_logic; DYNDELAY0: in  std_logic; 
            DQCLK0: out  std_logic; DQCLK1: out  std_logic);
    end component;
    component ECLKSYNCA
        port (ECLKI: in  std_logic; STOP: in  std_logic; 
            ECLKO: out  std_logic);
    end component;
    attribute ODDRAPPS : string; 
    attribute FREQUENCY_PIN_CLKOP : string; 
    attribute FREQUENCY_PIN_CLKOS : string; 
    attribute FREQUENCY_PIN_CLKI : string; 
    attribute FREQUENCY_PIN_CLKOK : string; 
    attribute IO_TYPE : string; 
    attribute IO_TYPE of Inst9_OB : label is "LVDS25";
    attribute ODDRAPPS of Inst8_ODDRX2D : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_3_4 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_3_3 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_3_2 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_3_1 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_3_0 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_2_4 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_2_3 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_2_2 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_2_1 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_2_0 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_1_4 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_1_3 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_1_2 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_1_1 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_1_0 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_0_4 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_0_3 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_0_2 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_0_1 : label is "ECLK_ALIGNED";
    attribute ODDRAPPS of Inst_ODDRX2D_0_0 : label is "ECLK_ALIGNED";
    attribute FREQUENCY_PIN_CLKOP of Inst2_EHXPLLF : label is "480.000000";
    attribute FREQUENCY_PIN_CLKOS of Inst2_EHXPLLF : label is "480.000000";
    attribute FREQUENCY_PIN_CLKI of Inst2_EHXPLLF : label is "240.000000";
    attribute FREQUENCY_PIN_CLKOK of Inst2_EHXPLLF : label is "240.000000";
    attribute IO_TYPE of Inst1_OB19 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB18 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB17 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB16 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB15 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB14 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB13 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB12 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB11 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB10 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB9 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB8 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB7 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB6 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB5 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB4 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB3 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB2 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB1 : label is "LVDS25";
    attribute IO_TYPE of Inst1_OB0 : label is "LVDS25";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    Inst9_OB: OB
        port map (I=>buf_clkout, O=>clkout);

    Inst8_ODDRX2D: ODDRX2D
        generic map (ISI_CAL=> "BYPASS", MEMMODE=> "ENABLED")
        port map (DA0=>scuba_vhi, DB0=>scuba_vlo, DA1=>scuba_vhi, 
            DB1=>scuba_vlo, SCLK=>sclk_t, DQCLK1=>dqclk14, 
            DQCLK0=>dqclk04, Q=>buf_clkout);

    Inst_ODDRX2D_3_4: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(19), DB0=>db0(19), DA1=>da1(19), DB1=>db1(19), 
            SCLK=>sclk_t, DQCLK1=>dqclk13, DQCLK0=>dqclk03, Q=>buf_qo19);

    Inst_ODDRX2D_3_3: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(18), DB0=>db0(18), DA1=>da1(18), DB1=>db1(18), 
            SCLK=>sclk_t, DQCLK1=>dqclk13, DQCLK0=>dqclk03, Q=>buf_qo18);

    Inst_ODDRX2D_3_2: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(17), DB0=>db0(17), DA1=>da1(17), DB1=>db1(17), 
            SCLK=>sclk_t, DQCLK1=>dqclk13, DQCLK0=>dqclk03, Q=>buf_qo17);

    Inst_ODDRX2D_3_1: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(16), DB0=>db0(16), DA1=>da1(16), DB1=>db1(16), 
            SCLK=>sclk_t, DQCLK1=>dqclk13, DQCLK0=>dqclk03, Q=>buf_qo16);

    Inst_ODDRX2D_3_0: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(15), DB0=>db0(15), DA1=>da1(15), DB1=>db1(15), 
            SCLK=>sclk_t, DQCLK1=>dqclk13, DQCLK0=>dqclk03, Q=>buf_qo15);

    Inst_ODDRX2D_2_4: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(14), DB0=>db0(14), DA1=>da1(14), DB1=>db1(14), 
            SCLK=>sclk_t, DQCLK1=>dqclk12, DQCLK0=>dqclk02, Q=>buf_qo14);

    Inst_ODDRX2D_2_3: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(13), DB0=>db0(13), DA1=>da1(13), DB1=>db1(13), 
            SCLK=>sclk_t, DQCLK1=>dqclk12, DQCLK0=>dqclk02, Q=>buf_qo13);

    Inst_ODDRX2D_2_2: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(12), DB0=>db0(12), DA1=>da1(12), DB1=>db1(12), 
            SCLK=>sclk_t, DQCLK1=>dqclk12, DQCLK0=>dqclk02, Q=>buf_qo12);

    Inst_ODDRX2D_2_1: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(11), DB0=>db0(11), DA1=>da1(11), DB1=>db1(11), 
            SCLK=>sclk_t, DQCLK1=>dqclk12, DQCLK0=>dqclk02, Q=>buf_qo11);

    Inst_ODDRX2D_2_0: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(10), DB0=>db0(10), DA1=>da1(10), DB1=>db1(10), 
            SCLK=>sclk_t, DQCLK1=>dqclk12, DQCLK0=>dqclk02, Q=>buf_qo10);

    Inst_ODDRX2D_1_4: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(9), DB0=>db0(9), DA1=>da1(9), DB1=>db1(9), 
            SCLK=>sclk_t, DQCLK1=>dqclk11, DQCLK0=>dqclk01, Q=>buf_qo9);

    Inst_ODDRX2D_1_3: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(8), DB0=>db0(8), DA1=>da1(8), DB1=>db1(8), 
            SCLK=>sclk_t, DQCLK1=>dqclk11, DQCLK0=>dqclk01, Q=>buf_qo8);

    Inst_ODDRX2D_1_2: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(7), DB0=>db0(7), DA1=>da1(7), DB1=>db1(7), 
            SCLK=>sclk_t, DQCLK1=>dqclk11, DQCLK0=>dqclk01, Q=>buf_qo7);

    Inst_ODDRX2D_1_1: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(6), DB0=>db0(6), DA1=>da1(6), DB1=>db1(6), 
            SCLK=>sclk_t, DQCLK1=>dqclk11, DQCLK0=>dqclk01, Q=>buf_qo6);

    Inst_ODDRX2D_1_0: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(5), DB0=>db0(5), DA1=>da1(5), DB1=>db1(5), 
            SCLK=>sclk_t, DQCLK1=>dqclk11, DQCLK0=>dqclk01, Q=>buf_qo5);

    Inst_ODDRX2D_0_4: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(4), DB0=>db0(4), DA1=>da1(4), DB1=>db1(4), 
            SCLK=>sclk_t, DQCLK1=>dqclk10, DQCLK0=>dqclk00, Q=>buf_qo4);

    Inst_ODDRX2D_0_3: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(3), DB0=>db0(3), DA1=>da1(3), DB1=>db1(3), 
            SCLK=>sclk_t, DQCLK1=>dqclk10, DQCLK0=>dqclk00, Q=>buf_qo3);

    Inst_ODDRX2D_0_2: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(2), DB0=>db0(2), DA1=>da1(2), DB1=>db1(2), 
            SCLK=>sclk_t, DQCLK1=>dqclk10, DQCLK0=>dqclk00, Q=>buf_qo2);

    Inst_ODDRX2D_0_1: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(1), DB0=>db0(1), DA1=>da1(1), DB1=>db1(1), 
            SCLK=>sclk_t, DQCLK1=>dqclk10, DQCLK0=>dqclk00, Q=>buf_qo1);

    Inst_ODDRX2D_0_0: ODDRX2D
        generic map (MEMMODE=> "DISABLED", ISI_CAL=> "BYPASS")
        port map (DA0=>da0(0), DB0=>db0(0), DA1=>da1(0), DB1=>db1(0), 
            SCLK=>sclk_t, DQCLK1=>dqclk10, DQCLK0=>dqclk00, Q=>buf_qo0);

    Inst7_DQSBUFE14: DQSBUFE1
        generic map (DYNDEL_VAL=>  0, DYNDEL_CNTL=> "DYNAMIC", 
        DYNDEL_TYPE=> "NORMAL")
        port map (ECLKW=>eclk, RST=>reset, DYNDELPOL=>scuba_vlo, 
            DYNDELAY6=>scuba_vlo, DYNDELAY5=>scuba_vlo, 
            DYNDELAY4=>scuba_vlo, DYNDELAY3=>scuba_vlo, 
            DYNDELAY2=>scuba_vlo, DYNDELAY1=>scuba_vlo, 
            DYNDELAY0=>scuba_vlo, DQCLK0=>dqclk04, DQCLK1=>dqclk14);

    Inst7_DQSBUFE13: DQSBUFE1
        generic map (DYNDEL_VAL=>  0, DYNDEL_CNTL=> "DYNAMIC", 
        DYNDEL_TYPE=> "NORMAL")
        port map (ECLKW=>eclk, RST=>reset, DYNDELPOL=>scuba_vlo, 
            DYNDELAY6=>scuba_vlo, DYNDELAY5=>scuba_vlo, 
            DYNDELAY4=>scuba_vlo, DYNDELAY3=>scuba_vlo, 
            DYNDELAY2=>scuba_vlo, DYNDELAY1=>scuba_vlo, 
            DYNDELAY0=>scuba_vlo, DQCLK0=>dqclk03, DQCLK1=>dqclk13);

    Inst7_DQSBUFE12: DQSBUFE1
        generic map (DYNDEL_VAL=>  0, DYNDEL_CNTL=> "DYNAMIC", 
        DYNDEL_TYPE=> "NORMAL")
        port map (ECLKW=>eclk, RST=>reset, DYNDELPOL=>scuba_vlo, 
            DYNDELAY6=>scuba_vlo, DYNDELAY5=>scuba_vlo, 
            DYNDELAY4=>scuba_vlo, DYNDELAY3=>scuba_vlo, 
            DYNDELAY2=>scuba_vlo, DYNDELAY1=>scuba_vlo, 
            DYNDELAY0=>scuba_vlo, DQCLK0=>dqclk02, DQCLK1=>dqclk12);

    Inst7_DQSBUFE11: DQSBUFE1
        generic map (DYNDEL_VAL=>  0, DYNDEL_CNTL=> "DYNAMIC", 
        DYNDEL_TYPE=> "NORMAL")
        port map (ECLKW=>eclk, RST=>reset, DYNDELPOL=>scuba_vlo, 
            DYNDELAY6=>scuba_vlo, DYNDELAY5=>scuba_vlo, 
            DYNDELAY4=>scuba_vlo, DYNDELAY3=>scuba_vlo, 
            DYNDELAY2=>scuba_vlo, DYNDELAY1=>scuba_vlo, 
            DYNDELAY0=>scuba_vlo, DQCLK0=>dqclk01, DQCLK1=>dqclk11);

    Inst7_DQSBUFE10: DQSBUFE1
        generic map (DYNDEL_VAL=>  0, DYNDEL_CNTL=> "DYNAMIC", 
        DYNDEL_TYPE=> "NORMAL")
        port map (ECLKW=>eclk, RST=>reset, DYNDELPOL=>scuba_vlo, 
            DYNDELAY6=>scuba_vlo, DYNDELAY5=>scuba_vlo, 
            DYNDELAY4=>scuba_vlo, DYNDELAY3=>scuba_vlo, 
            DYNDELAY2=>scuba_vlo, DYNDELAY1=>scuba_vlo, 
            DYNDELAY0=>scuba_vlo, DQCLK0=>dqclk00, DQCLK1=>dqclk10);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    Inst6_CLKDIVB: CLKDIVB
        port map (CLKI=>eclk, RST=>reset, RELEASE=>scuba_vhi, 
            CDIV1=>cdiv1, CDIV2=>sclk_t, CDIV4=>cdiv4, CDIV8=>cdiv8);

    Inst5_ECLKSYNCA: ECLKSYNCA
        port map (ECLKI=>clkop, STOP=>reset_d2, ECLKO=>eclk);

    Inst4_FD1S3BX: FD1S3BX
        port map (D=>reset_d1, CK=>clkok, PD=>reset, Q=>reset_d2);

    Inst3_FD1S3BX: FD1S3BX
        port map (D=>reset, CK=>clkok, PD=>reset, Q=>reset_d1);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    Inst2_EHXPLLF: EHXPLLF
        generic map (FEEDBK_PATH=> "INTERNAL", CLKOK_BYPASS=> "DISABLED", 
        CLKOS_BYPASS=> "DISABLED", CLKOP_BYPASS=> "DISABLED", 
        CLKOK_INPUT=> "CLKOS", DELAY_PWD=> "DISABLED", DELAY_VAL=>  0, 
        CLKOS_TRIM_DELAY=>  0, CLKOS_TRIM_POL=> "RISING", 
        CLKOP_TRIM_DELAY=>  0, CLKOP_TRIM_POL=> "RISING", 
        PHASE_DELAY_CNTL=> "STATIC", DUTY=>  8, PHASEADJ=> "0.0", 
        CLKOK_DIV=>  2, CLKOP_DIV=>  2, CLKFB_DIV=>  2, CLKI_DIV=>  1, 
        FIN=> "240.000000")
        port map (CLKI=>clk, CLKFB=>clkintfb, RST=>pll_reset, 
            RSTK=>scuba_vlo, WRDEL=>scuba_vlo, DRPAI3=>scuba_vlo, 
            DRPAI2=>scuba_vlo, DRPAI1=>scuba_vlo, DRPAI0=>scuba_vlo, 
            DFPAI3=>scuba_vlo, DFPAI2=>scuba_vlo, DFPAI1=>scuba_vlo, 
            DFPAI0=>scuba_vlo, FDA3=>scuba_vlo, FDA2=>scuba_vlo, 
            FDA1=>scuba_vlo, FDA0=>scuba_vlo, CLKOP=>clkop, CLKOS=>clkos, 
            CLKOK=>clkok, CLKOK2=>clkok2, LOCK=>pll_lock, 
            CLKINTFB=>clkintfb);

    Inst1_OB19: OB
        port map (I=>buf_qo19, O=>q(19));

    Inst1_OB18: OB
        port map (I=>buf_qo18, O=>q(18));

    Inst1_OB17: OB
        port map (I=>buf_qo17, O=>q(17));

    Inst1_OB16: OB
        port map (I=>buf_qo16, O=>q(16));

    Inst1_OB15: OB
        port map (I=>buf_qo15, O=>q(15));

    Inst1_OB14: OB
        port map (I=>buf_qo14, O=>q(14));

    Inst1_OB13: OB
        port map (I=>buf_qo13, O=>q(13));

    Inst1_OB12: OB
        port map (I=>buf_qo12, O=>q(12));

    Inst1_OB11: OB
        port map (I=>buf_qo11, O=>q(11));

    Inst1_OB10: OB
        port map (I=>buf_qo10, O=>q(10));

    Inst1_OB9: OB
        port map (I=>buf_qo9, O=>q(9));

    Inst1_OB8: OB
        port map (I=>buf_qo8, O=>q(8));

    Inst1_OB7: OB
        port map (I=>buf_qo7, O=>q(7));

    Inst1_OB6: OB
        port map (I=>buf_qo6, O=>q(6));

    Inst1_OB5: OB
        port map (I=>buf_qo5, O=>q(5));

    Inst1_OB4: OB
        port map (I=>buf_qo4, O=>q(4));

    Inst1_OB3: OB
        port map (I=>buf_qo3, O=>q(3));

    Inst1_OB2: OB
        port map (I=>buf_qo2, O=>q(2));

    Inst1_OB1: OB
        port map (I=>buf_qo1, O=>q(1));

    Inst1_OB0: OB
        port map (I=>buf_qo0, O=>q(0));

    sclk <= sclk_t;
end Structure;

-- synopsys translate_off
library ecp3;
configuration Structure_CON of ddr_20 is
    for Structure
        for all:EHXPLLF use entity ecp3.EHXPLLF(V); end for;
        for all:FD1S3BX use entity ecp3.FD1S3BX(V); end for;
        for all:VHI use entity ecp3.VHI(V); end for;
        for all:VLO use entity ecp3.VLO(V); end for;
        for all:OB use entity ecp3.OB(V); end for;
        for all:CLKDIVB use entity ecp3.CLKDIVB(V); end for;
        for all:ODDRX2D use entity ecp3.ODDRX2D(V); end for;
        for all:DQSBUFE1 use entity ecp3.DQSBUFE1(V); end for;
        for all:ECLKSYNCA use entity ecp3.ECLKSYNCA(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
