-- VHDL module instantiation generated by SCUBA Diamond_1.3_Production (92)
-- Module  Version: 5.4
-- Mon Sep 12 17:38:42 2011

-- parameterized module component declaration
component lattice_ecp3_fifo_18x16_dualport
    port (Data: in  std_logic_vector(17 downto 0); 
        WrClock: in  std_logic; RdClock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        RPReset: in  std_logic; Q: out  std_logic_vector(17 downto 0); 
        Empty: out  std_logic; Full: out  std_logic; 
        AlmostFull: out  std_logic);
end component;

-- parameterized module component instance
__ : lattice_ecp3_fifo_18x16_dualport
    port map (Data(17 downto 0)=>__, WrClock=>__, RdClock=>__, WrEn=>__, 
        RdEn=>__, Reset=>__, RPReset=>__, Q(17 downto 0)=>__, Empty=>__, 
        Full=>__, AlmostFull=>__);
