-- VHDL module instantiation generated by SCUBA Diamond_1.3_Production (92)
-- Module  Version: 4.8
-- Tue Sep 13 10:20:31 2011

-- parameterized module component declaration
component lattice_ecp3_fifo_18x1k
    port (Data: in  std_logic_vector(17 downto 0); Clock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        Q: out  std_logic_vector(17 downto 0); Empty: out  std_logic; 
        Full: out  std_logic; AlmostFull: out  std_logic);
end component;

-- parameterized module component instance
__ : lattice_ecp3_fifo_18x1k
    port map (Data(17 downto 0)=>__, Clock=>__, WrEn=>__, RdEn=>__, 
        Reset=>__, Q(17 downto 0)=>__, Empty=>__, Full=>__, AlmostFull=>__);
