/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.1.502 */
/* Module Version: 5.7 */
/* Thu Sep 01 10:19:13 2016 */

/* parameterized module instance */
Cpll3 __ (.CLK( ), .FINEDELB0( ), .FINEDELB1( ), .FINEDELB2( ), 
    .FINEDELB3( ), .DPHASE0( ), .DPHASE1( ), .DPHASE2( ), .DPHASE3( ), 
    .CLKOP( ), .CLKOS( ), .LOCK( ));
