/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.7 */
/* Mon Apr 10 12:20:51 2017 */

/* parameterized module instance */
Cpll1 __ (.CLK( ), .FINEDELB0( ), .FINEDELB1( ), .FINEDELB2( ), 
    .FINEDELB3( ), .DPHASE0( ), .DPHASE1( ), .DPHASE2( ), .DPHASE3( ), 
    .DDUTY0( ), .DDUTY1( ), .DDUTY2( ), .DDUTY3( ), .CLKOP( ), .CLKOS( ), 
    .LOCK( ));
