/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.1.502 */
/* Module Version: 5.8 */
/* Wed Mar 01 16:07:08 2017 */

/* parameterized module instance */
readoutfifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .WCNT( ), .RCNT( ), .Empty( ), 
    .Full( ));
