/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.1.502 */
/* Module Version: 5.1 */
/* Wed Sep 28 09:41:09 2016 */

/* parameterized module instance */
testfifo __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), .Q( ), 
    .WCNT( ), .Empty( ), .Full( ));
