/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.7.1.502 */
/* Module Version: 5.1 */
/* D:\Cad\lscc\diamond\3.7_x64\ispfpga\bin\nt64\scuba.exe -w -n testfifo -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type ebfifo -depth 32 -width 16 -depth 32 -no_enable -pe -1 -pf -1 -fill  */
/* Wed Sep 28 09:41:09 2016 */


`timescale 1 ns / 1 ps
module testfifo (Data, Clock, WrEn, RdEn, Reset, Q, WCNT, Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] Data;
    input wire Clock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    output wire [15:0] Q;
    output wire [5:0] WCNT;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire rden_i_inv;
    wire fcnt_en;
    wire empty_i;
    wire empty_d;
    wire full_i;
    wire full_d;
    wire ifcount_0;
    wire ifcount_1;
    wire bdcnt_bctr_ci;
    wire ifcount_2;
    wire ifcount_3;
    wire co0;
    wire ifcount_4;
    wire ifcount_5;
    wire co2;
    wire cnt_con;
    wire co1;
    wire cmp_ci;
    wire rden_i;
    wire co0_1;
    wire co1_1;
    wire cmp_le_1;
    wire cmp_le_1_c;
    wire cmp_ci_1;
    wire fcount_0;
    wire fcount_1;
    wire co0_2;
    wire fcount_2;
    wire fcount_3;
    wire co1_2;
    wire wren_i;
    wire wren_i_inv;
    wire fcount_4;
    wire fcount_5;
    wire cmp_ge_d1;
    wire cmp_ge_d1_c;
    wire iwcount_0;
    wire iwcount_1;
    wire w_ctr_ci;
    wire wcount_0;
    wire wcount_1;
    wire iwcount_2;
    wire iwcount_3;
    wire co0_3;
    wire wcount_2;
    wire wcount_3;
    wire iwcount_4;
    wire iwcount_5;
    wire co2_1;
    wire co1_3;
    wire wcount_4;
    wire wcount_5;
    wire scuba_vlo;
    wire scuba_vhi;
    wire ircount_0;
    wire ircount_1;
    wire r_ctr_ci;
    wire rcount_0;
    wire rcount_1;
    wire ircount_2;
    wire ircount_3;
    wire co0_4;
    wire rcount_2;
    wire rcount_3;
    wire ircount_4;
    wire ircount_5;
    wire co2_2;
    wire co1_4;
    wire rcount_4;
    wire rcount_5;

    AND2 AND2_t3 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_3 (.A(full_i), .Z(invout_1));

    AND2 AND2_t2 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_2 (.A(empty_i), .Z(invout_0));

    AND2 AND2_t1 (.A(wren_i), .B(rden_i_inv), .Z(cnt_con));

    XOR2 XOR2_t0 (.A(wren_i), .B(rden_i), .Z(fcnt_en));

    INV INV_1 (.A(rden_i), .Z(rden_i_inv));

    INV INV_0 (.A(wren_i), .Z(wren_i_inv));

    defparam LUT4_1.initval =  16'h3232 ;
    ROM16X1A LUT4_1 (.AD3(scuba_vlo), .AD2(cmp_le_1), .AD1(wren_i), .AD0(empty_i), 
        .DO0(empty_d));

    defparam LUT4_0.initval =  16'h3232 ;
    ROM16X1A LUT4_0 (.AD3(scuba_vlo), .AD2(cmp_ge_d1), .AD1(rden_i), .AD0(full_i), 
        .DO0(full_d));

    defparam pdp_ram_0_0_0.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_0_0.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_0_0.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_0_0.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_0_0.GSR = "DISABLED" ;
    defparam pdp_ram_0_0_0.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_0_0.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_0_0.DATA_WIDTH_B = 18 ;
    defparam pdp_ram_0_0_0.DATA_WIDTH_A = 18 ;
    DP16KC pdp_ram_0_0_0 (.DIA0(Data[0]), .DIA1(Data[1]), .DIA2(Data[2]), 
        .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), .DIA6(Data[6]), 
        .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(Data[9]), .DIA10(Data[10]), 
        .DIA11(Data[11]), .DIA12(Data[12]), .DIA13(Data[13]), .DIA14(Data[14]), 
        .DIA15(Data[15]), .DIA16(scuba_vlo), .DIA17(scuba_vlo), .ADA0(scuba_vhi), 
        .ADA1(scuba_vhi), .ADA2(scuba_vlo), .ADA3(scuba_vlo), .ADA4(wcount_0), 
        .ADA5(wcount_1), .ADA6(wcount_2), .ADA7(wcount_3), .ADA8(wcount_4), 
        .ADA9(scuba_vlo), .ADA10(scuba_vlo), .ADA11(scuba_vlo), .ADA12(scuba_vlo), 
        .ADA13(scuba_vlo), .CEA(wren_i), .CLKA(Clock), .OCEA(wren_i), .WEA(scuba_vhi), 
        .CSA0(scuba_vlo), .CSA1(scuba_vlo), .CSA2(scuba_vlo), .RSTA(Reset), 
        .DIB0(scuba_vlo), .DIB1(scuba_vlo), .DIB2(scuba_vlo), .DIB3(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB5(scuba_vlo), .DIB6(scuba_vlo), .DIB7(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB9(scuba_vlo), .DIB10(scuba_vlo), .DIB11(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB13(scuba_vlo), .DIB14(scuba_vlo), .DIB15(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB17(scuba_vlo), .ADB0(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB2(scuba_vlo), .ADB3(scuba_vlo), .ADB4(rcount_0), .ADB5(rcount_1), 
        .ADB6(rcount_2), .ADB7(rcount_3), .ADB8(rcount_4), .ADB9(scuba_vlo), 
        .ADB10(scuba_vlo), .ADB11(scuba_vlo), .ADB12(scuba_vlo), .ADB13(scuba_vlo), 
        .CEB(rden_i), .CLKB(Clock), .OCEB(rden_i), .WEB(scuba_vlo), .CSB0(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), .DOA0(), .DOA1(), 
        .DOA2(), .DOA3(), .DOA4(), .DOA5(), .DOA6(), .DOA7(), .DOA8(), .DOA9(), 
        .DOA10(), .DOA11(), .DOA12(), .DOA13(), .DOA14(), .DOA15(), .DOA16(), 
        .DOA17(), .DOB0(Q[0]), .DOB1(Q[1]), .DOB2(Q[2]), .DOB3(Q[3]), .DOB4(Q[4]), 
        .DOB5(Q[5]), .DOB6(Q[6]), .DOB7(Q[7]), .DOB8(Q[8]), .DOB9(Q[9]), 
        .DOB10(Q[10]), .DOB11(Q[11]), .DOB12(Q[12]), .DOB13(Q[13]), .DOB14(Q[14]), 
        .DOB15(Q[15]), .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="testfifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis RESETMODE="SYNC" */;

    FD1P3DX FF_19 (.D(ifcount_0), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(ifcount_1), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(ifcount_2), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(ifcount_3), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(ifcount_4), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(ifcount_5), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_13 (.D(empty_d), .CK(Clock), .PD(Reset), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_12 (.D(full_d), .CK(Clock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(iwcount_0), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(iwcount_1), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(iwcount_2), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(iwcount_3), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(iwcount_4), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(iwcount_5), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(ircount_0), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(ircount_1), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(ircount_2), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(ircount_3), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(ircount_4), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(ircount_5), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FADD2B bdcnt_bctr_cia (.A0(scuba_vlo), .A1(cnt_con), .B0(scuba_vlo), 
        .B1(cnt_con), .CI(scuba_vlo), .COUT(bdcnt_bctr_ci), .S0(), .S1());

    CB2 bdcnt_bctr_0 (.CI(bdcnt_bctr_ci), .PC0(fcount_0), .PC1(fcount_1), 
        .CON(cnt_con), .CO(co0), .NC0(ifcount_0), .NC1(ifcount_1));

    CB2 bdcnt_bctr_1 (.CI(co0), .PC0(fcount_2), .PC1(fcount_3), .CON(cnt_con), 
        .CO(co1), .NC0(ifcount_2), .NC1(ifcount_3));

    CB2 bdcnt_bctr_2 (.CI(co1), .PC0(fcount_4), .PC1(fcount_5), .CON(cnt_con), 
        .CO(co2), .NC0(ifcount_4), .NC1(ifcount_5));

    FADD2B e_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(cmp_ci), .S0(), .S1());

    ALEB2 e_cmp_0 (.A0(fcount_0), .A1(fcount_1), .B0(rden_i), .B1(scuba_vlo), 
        .CI(cmp_ci), .LE(co0_1));

    ALEB2 e_cmp_1 (.A0(fcount_2), .A1(fcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co0_1), .LE(co1_1));

    ALEB2 e_cmp_2 (.A0(fcount_4), .A1(fcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co1_1), .LE(cmp_le_1_c));

    FADD2B a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(cmp_le_1_c), .COUT(), .S0(cmp_le_1), .S1());

    FADD2B g_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(cmp_ci_1), .S0(), .S1());

    AGEB2 g_cmp_0 (.A0(fcount_0), .A1(fcount_1), .B0(wren_i), .B1(wren_i), 
        .CI(cmp_ci_1), .GE(co0_2));

    AGEB2 g_cmp_1 (.A0(fcount_2), .A1(fcount_3), .B0(wren_i), .B1(wren_i), 
        .CI(co0_2), .GE(co1_2));

    AGEB2 g_cmp_2 (.A0(fcount_4), .A1(fcount_5), .B0(wren_i), .B1(wren_i_inv), 
        .CI(co1_2), .GE(cmp_ge_d1_c));

    FADD2B a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(cmp_ge_d1_c), .COUT(), .S0(cmp_ge_d1), .S1());

    FADD2B w_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(w_ctr_ci), .S0(), .S1());

    CU2 w_ctr_0 (.CI(w_ctr_ci), .PC0(wcount_0), .PC1(wcount_1), .CO(co0_3), 
        .NC0(iwcount_0), .NC1(iwcount_1));

    CU2 w_ctr_1 (.CI(co0_3), .PC0(wcount_2), .PC1(wcount_3), .CO(co1_3), 
        .NC0(iwcount_2), .NC1(iwcount_3));

    CU2 w_ctr_2 (.CI(co1_3), .PC0(wcount_4), .PC1(wcount_5), .CO(co2_1), 
        .NC0(iwcount_4), .NC1(iwcount_5));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B r_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(r_ctr_ci), .S0(), .S1());

    CU2 r_ctr_0 (.CI(r_ctr_ci), .PC0(rcount_0), .PC1(rcount_1), .CO(co0_4), 
        .NC0(ircount_0), .NC1(ircount_1));

    CU2 r_ctr_1 (.CI(co0_4), .PC0(rcount_2), .PC1(rcount_3), .CO(co1_4), 
        .NC0(ircount_2), .NC1(ircount_3));

    CU2 r_ctr_2 (.CI(co1_4), .PC0(rcount_4), .PC1(rcount_5), .CO(co2_2), 
        .NC0(ircount_4), .NC1(ircount_5));

    assign WCNT[0] = fcount_0;
    assign WCNT[1] = fcount_1;
    assign WCNT[2] = fcount_2;
    assign WCNT[3] = fcount_3;
    assign WCNT[4] = fcount_4;
    assign WCNT[5] = fcount_5;
    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_0 MEM_LPC_FILE testfifo.lpc
    // exemplar attribute pdp_ram_0_0_0 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_0_0 RESETMODE SYNC
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
