-- VHDL netlist generated by SCUBA ispLever_v70_Prod_Build (55)
-- Module  Version: 4.2
--/opt/lattice/isplever7.0/isptools/ispfpga/bin/lin/scuba -w -n flexi_PCS_fifo_LUT -lang vhdl -synth synplify -bus_exp 7 -bb -arch or5s00 -type ebfifo -depth 8 -width 18 -rwidth 18 -pfu_fifo -no_enable -pe 3 -pf 6 -e 

-- Fri Nov 23 08:28:34 2007

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library SCM;
use SCM.COMPONENTS.all;
-- synopsys translate_on

entity flexi_PCS_fifo_LUT is
    port (
        Data: in  std_logic_vector(17 downto 0); 
        WrClock: in  std_logic; 
        RdClock: in  std_logic; 
        WrEn: in  std_logic; 
        RdEn: in  std_logic; 
        Reset: in  std_logic; 
        RPReset: in  std_logic; 
        Q: out  std_logic_vector(17 downto 0); 
        Empty: out  std_logic; 
        Full: out  std_logic; 
        AlmostEmpty: out  std_logic; 
        AlmostFull: out  std_logic);
end flexi_PCS_fifo_LUT;

architecture Structure of flexi_PCS_fifo_LUT is

    -- internal signal declarations
    signal invout_1: std_logic;
    signal invout_0: std_logic;
    signal w_gdata_0: std_logic;
    signal w_gdata_1: std_logic;
    signal w_gdata_2: std_logic;
    signal wptr_3: std_logic;
    signal r_gdata_0: std_logic;
    signal r_gdata_1: std_logic;
    signal r_gdata_2: std_logic;
    signal rptr_3: std_logic;
    signal w_gcount_0: std_logic;
    signal w_gcount_1: std_logic;
    signal w_gcount_2: std_logic;
    signal w_gcount_3: std_logic;
    signal r_gcount_0: std_logic;
    signal r_gcount_1: std_logic;
    signal r_gcount_2: std_logic;
    signal r_gcount_3: std_logic;
    signal w_gcount_r20: std_logic;
    signal w_gcount_r0: std_logic;
    signal w_gcount_r21: std_logic;
    signal w_gcount_r1: std_logic;
    signal w_gcount_r22: std_logic;
    signal w_gcount_r2: std_logic;
    signal w_gcount_r23: std_logic;
    signal w_gcount_r3: std_logic;
    signal r_gcount_w20: std_logic;
    signal r_gcount_w0: std_logic;
    signal r_gcount_w21: std_logic;
    signal r_gcount_w1: std_logic;
    signal r_gcount_w22: std_logic;
    signal r_gcount_w2: std_logic;
    signal r_gcount_w23: std_logic;
    signal r_gcount_w3: std_logic;
    signal empty_i: std_logic;
    signal full_i: std_logic;
    signal rRst: std_logic;
    signal iwcount_0: std_logic;
    signal iwcount_1: std_logic;
    signal iwcount_2: std_logic;
    signal iwcount_3: std_logic;
    signal co1: std_logic;
    signal wcount_3: std_logic;
    signal co0: std_logic;
    signal ircount_0: std_logic;
    signal ircount_1: std_logic;
    signal ircount_2: std_logic;
    signal ircount_3: std_logic;
    signal co1_1: std_logic;
    signal rcount_3: std_logic;
    signal co0_1: std_logic;
    signal rcount_0: std_logic;
    signal rcount_1: std_logic;
    signal co0_2: std_logic;
    signal empty_cmp_clr: std_logic;
    signal rcount_2: std_logic;
    signal empty_cmp_set: std_logic;
    signal empty_d: std_logic;
    signal empty_d_c: std_logic;
    signal wcount_0: std_logic;
    signal wcount_1: std_logic;
    signal co0_3: std_logic;
    signal full_cmp_clr: std_logic;
    signal wcount_2: std_logic;
    signal full_cmp_set: std_logic;
    signal full_d: std_logic;
    signal full_d_c: std_logic;
    signal iae_setcount_0: std_logic;
    signal iae_setcount_1: std_logic;
    signal iae_setcount_2: std_logic;
    signal iae_setcount_3: std_logic;
    signal co1_2: std_logic;
    signal ae_setcount_3: std_logic;
    signal co0_4: std_logic;
    signal rden_i: std_logic;
    signal w_g2b_xor_cluster_0: std_logic;
    signal wcount_r1: std_logic;
    signal ae_setcount_0: std_logic;
    signal ae_setcount_1: std_logic;
    signal co0_5: std_logic;
    signal wcount_r2: std_logic;
    signal ae_set_cmp_clr: std_logic;
    signal ae_setcount_2: std_logic;
    signal ae_set_cmp_set: std_logic;
    signal ae_set_d: std_logic;
    signal ae_set_d_c: std_logic;
    signal iaf_setcount_0: std_logic;
    signal iaf_setcount_1: std_logic;
    signal iaf_setcount_2: std_logic;
    signal iaf_setcount_3: std_logic;
    signal co1_3: std_logic;
    signal af_setcount_3: std_logic;
    signal co0_6: std_logic;
    signal r_g2b_xor_cluster_0: std_logic;
    signal rcount_w1: std_logic;
    signal af_setcount_0: std_logic;
    signal af_setcount_1: std_logic;
    signal co0_7: std_logic;
    signal rcount_w2: std_logic;
    signal af_set_cmp_clr: std_logic;
    signal af_setcount_2: std_logic;
    signal af_set_cmp_set: std_logic;
    signal af_set: std_logic;
    signal af_set_c: std_logic;
    signal rdataout17: std_logic;
    signal rdataout16: std_logic;
    signal rdataout15: std_logic;
    signal rdataout14: std_logic;
    signal rdataout13: std_logic;
    signal rdataout12: std_logic;
    signal rdataout11: std_logic;
    signal rdataout10: std_logic;
    signal rdataout9: std_logic;
    signal rdataout8: std_logic;
    signal rdataout7: std_logic;
    signal rdataout6: std_logic;
    signal rdataout5: std_logic;
    signal rdataout4: std_logic;
    signal rdataout3: std_logic;
    signal rdataout2: std_logic;
    signal rdataout1: std_logic;
    signal rdataout0: std_logic;
    signal rptr_0: std_logic;
    signal rptr_1: std_logic;
    signal rptr_2: std_logic;
    signal wren_i: std_logic;
    signal scuba_vhi: std_logic;
    signal wptr_0: std_logic;
    signal wptr_1: std_logic;
    signal wptr_2: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component DPR16X2
    -- synopsys translate_off
        generic (INITVAL : in String; GSR : in String);
    -- synopsys translate_on
        port (DI0: in  std_logic; DI1: in  std_logic; 
            WAD3: in  std_logic; WAD2: in  std_logic; 
            WAD1: in  std_logic; WAD0: in  std_logic; WRE: in  std_logic; 
            WPE: in  std_logic; WCK: in  std_logic; RAD3: in  std_logic; 
            RAD2: in  std_logic; RAD1: in  std_logic; 
            RAD0: in  std_logic; WDO0: out  std_logic; 
            WDO1: out  std_logic; RDO0: out  std_logic; 
            RDO1: out  std_logic);
    end component;
    component ROM16X1
    -- synopsys translate_off
        generic (initval : in String);
    -- synopsys translate_on
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component AND2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component OR2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component XOR2
        port (A: in  std_logic; B: in  std_logic; Z: out  std_logic);
    end component;
    component INV
        port (A: in  std_logic; Z: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component FADD2
        port (A1: in  std_logic; A0: in  std_logic; B1: in  std_logic; 
            B0: in  std_logic; CI: in  std_logic; COUT1: out  std_logic; 
            COUT0: out  std_logic; S1: out  std_logic; 
            S0: out  std_logic);
    end component;
    component CU2
        port (CI: in  std_logic; PC1: in  std_logic; PC0: in  std_logic; 
            CO: out  std_logic; NC1: out  std_logic; NC0: out  std_logic);
    end component;
    component AGEB2
        port (A1: in  std_logic; A0: in  std_logic; B1: in  std_logic; 
            B0: in  std_logic; CI: in  std_logic; GE: out  std_logic);
    end component;
    component FD1P3BX
    -- synopsys translate_off
        generic (GSR : in String);
    -- synopsys translate_on
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            PD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1P3DX
    -- synopsys translate_off
        generic (GSR : in String);
    -- synopsys translate_on
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component FD1S3BX
    -- synopsys translate_off
        generic (GSR : in String);
    -- synopsys translate_on
        port (D: in  std_logic; CK: in  std_logic; PD: in  std_logic; 
            Q: out  std_logic);
    end component;
    component FD1S3DX
    -- synopsys translate_off
        generic (GSR : in String);
    -- synopsys translate_on
        port (D: in  std_logic; CK: in  std_logic; CD: in  std_logic; 
            Q: out  std_logic);
    end component;
    attribute GSR : string; 
    attribute initval : string; 
    attribute initval of LUT4_13 : label is "0x6996";
    attribute initval of LUT4_12 : label is "0x6996";
    attribute initval of LUT4_11 : label is "0x6996";
    attribute initval of LUT4_10 : label is "0x6996";
    attribute initval of LUT4_9 : label is "0x6996";
    attribute initval of LUT4_8 : label is "0x6996";
    attribute initval of LUT4_7 : label is "0x0410";
    attribute initval of LUT4_6 : label is "0x1004";
    attribute initval of LUT4_5 : label is "0x0140";
    attribute initval of LUT4_4 : label is "0x4001";
    attribute initval of LUT4_3 : label is "0x13c8";
    attribute initval of LUT4_2 : label is "0x2004";
    attribute initval of LUT4_1 : label is "0x4c32";
    attribute initval of LUT4_0 : label is "0x8001";
    attribute GSR of FF_69 : label is "ENABLED";
    attribute GSR of FF_68 : label is "ENABLED";
    attribute GSR of FF_67 : label is "ENABLED";
    attribute GSR of FF_66 : label is "ENABLED";
    attribute GSR of FF_65 : label is "ENABLED";
    attribute GSR of FF_64 : label is "ENABLED";
    attribute GSR of FF_63 : label is "ENABLED";
    attribute GSR of FF_62 : label is "ENABLED";
    attribute GSR of FF_61 : label is "ENABLED";
    attribute GSR of FF_60 : label is "ENABLED";
    attribute GSR of FF_59 : label is "ENABLED";
    attribute GSR of FF_58 : label is "ENABLED";
    attribute GSR of FF_57 : label is "ENABLED";
    attribute GSR of FF_56 : label is "ENABLED";
    attribute GSR of FF_55 : label is "ENABLED";
    attribute GSR of FF_54 : label is "ENABLED";
    attribute GSR of FF_53 : label is "ENABLED";
    attribute GSR of FF_52 : label is "ENABLED";
    attribute GSR of FF_51 : label is "ENABLED";
    attribute GSR of FF_50 : label is "ENABLED";
    attribute GSR of FF_49 : label is "ENABLED";
    attribute GSR of FF_48 : label is "ENABLED";
    attribute GSR of FF_47 : label is "ENABLED";
    attribute GSR of FF_46 : label is "ENABLED";
    attribute GSR of FF_45 : label is "ENABLED";
    attribute GSR of FF_44 : label is "ENABLED";
    attribute GSR of FF_43 : label is "ENABLED";
    attribute GSR of FF_42 : label is "ENABLED";
    attribute GSR of FF_41 : label is "ENABLED";
    attribute GSR of FF_40 : label is "ENABLED";
    attribute GSR of FF_39 : label is "ENABLED";
    attribute GSR of FF_38 : label is "ENABLED";
    attribute GSR of FF_37 : label is "ENABLED";
    attribute GSR of FF_36 : label is "ENABLED";
    attribute GSR of FF_35 : label is "ENABLED";
    attribute GSR of FF_34 : label is "ENABLED";
    attribute GSR of FF_33 : label is "ENABLED";
    attribute GSR of FF_32 : label is "ENABLED";
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute GSR of fifo_pfu_0_0 : label is "ENABLED";
    attribute initval of fifo_pfu_0_0 : label is "0x0000000000000000";
    attribute GSR of fifo_pfu_0_1 : label is "ENABLED";
    attribute initval of fifo_pfu_0_1 : label is "0x0000000000000000";
    attribute GSR of fifo_pfu_0_2 : label is "ENABLED";
    attribute initval of fifo_pfu_0_2 : label is "0x0000000000000000";
    attribute GSR of fifo_pfu_0_3 : label is "ENABLED";
    attribute initval of fifo_pfu_0_3 : label is "0x0000000000000000";
    attribute GSR of fifo_pfu_0_4 : label is "ENABLED";
    attribute initval of fifo_pfu_0_4 : label is "0x0000000000000000";
    attribute GSR of fifo_pfu_0_5 : label is "ENABLED";
    attribute initval of fifo_pfu_0_5 : label is "0x0000000000000000";
    attribute GSR of fifo_pfu_0_6 : label is "ENABLED";
    attribute initval of fifo_pfu_0_6 : label is "0x0000000000000000";
    attribute GSR of fifo_pfu_0_7 : label is "ENABLED";
    attribute initval of fifo_pfu_0_7 : label is "0x0000000000000000";
    attribute GSR of fifo_pfu_0_8 : label is "ENABLED";
    attribute initval of fifo_pfu_0_8 : label is "0x0000000000000000";
    attribute syn_keep : boolean;

begin
    -- component instantiation statements
    AND2_t8: AND2
        port map (A=>WrEn, B=>invout_1, Z=>wren_i);

    INV_1: INV
        port map (A=>full_i, Z=>invout_1);

    AND2_t7: AND2
        port map (A=>RdEn, B=>invout_0, Z=>rden_i);

    INV_0: INV
        port map (A=>empty_i, Z=>invout_0);

    OR2_t6: OR2
        port map (A=>Reset, B=>RPReset, Z=>rRst);

    XOR2_t5: XOR2
        port map (A=>wcount_0, B=>wcount_1, Z=>w_gdata_0);

    XOR2_t4: XOR2
        port map (A=>wcount_1, B=>wcount_2, Z=>w_gdata_1);

    XOR2_t3: XOR2
        port map (A=>wcount_2, B=>wcount_3, Z=>w_gdata_2);

    XOR2_t2: XOR2
        port map (A=>rcount_0, B=>rcount_1, Z=>r_gdata_0);

    XOR2_t1: XOR2
        port map (A=>rcount_1, B=>rcount_2, Z=>r_gdata_1);

    XOR2_t0: XOR2
        port map (A=>rcount_2, B=>rcount_3, Z=>r_gdata_2);

    LUT4_13: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x6996")
        -- synopsys translate_on
        port map (AD3=>w_gcount_r20, AD2=>w_gcount_r21, 
            AD1=>w_gcount_r22, AD0=>w_gcount_r23, 
            DO0=>w_g2b_xor_cluster_0);

    LUT4_12: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x6996")
        -- synopsys translate_on
        port map (AD3=>w_gcount_r22, AD2=>w_gcount_r23, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>wcount_r2);

    LUT4_11: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x6996")
        -- synopsys translate_on
        port map (AD3=>w_gcount_r21, AD2=>w_gcount_r22, 
            AD1=>w_gcount_r23, AD0=>scuba_vlo, DO0=>wcount_r1);

    LUT4_10: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x6996")
        -- synopsys translate_on
        port map (AD3=>r_gcount_w20, AD2=>r_gcount_w21, 
            AD1=>r_gcount_w22, AD0=>r_gcount_w23, 
            DO0=>r_g2b_xor_cluster_0);

    LUT4_9: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x6996")
        -- synopsys translate_on
        port map (AD3=>r_gcount_w22, AD2=>r_gcount_w23, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>rcount_w2);

    LUT4_8: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x6996")
        -- synopsys translate_on
        port map (AD3=>r_gcount_w21, AD2=>r_gcount_w22, 
            AD1=>r_gcount_w23, AD0=>scuba_vlo, DO0=>rcount_w1);

    LUT4_7: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x0410")
        -- synopsys translate_on
        port map (AD3=>rptr_3, AD2=>rcount_3, AD1=>w_gcount_r23, 
            AD0=>scuba_vlo, DO0=>empty_cmp_set);

    LUT4_6: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x1004")
        -- synopsys translate_on
        port map (AD3=>rptr_3, AD2=>rcount_3, AD1=>w_gcount_r23, 
            AD0=>scuba_vlo, DO0=>empty_cmp_clr);

    LUT4_5: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x0140")
        -- synopsys translate_on
        port map (AD3=>wptr_3, AD2=>wcount_3, AD1=>r_gcount_w23, 
            AD0=>scuba_vlo, DO0=>full_cmp_set);

    LUT4_4: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x4001")
        -- synopsys translate_on
        port map (AD3=>wptr_3, AD2=>wcount_3, AD1=>r_gcount_w23, 
            AD0=>scuba_vlo, DO0=>full_cmp_clr);

    LUT4_3: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x13c8")
        -- synopsys translate_on
        port map (AD3=>ae_setcount_3, AD2=>rcount_3, AD1=>w_gcount_r23, 
            AD0=>rptr_3, DO0=>ae_set_cmp_set);

    LUT4_2: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x2004")
        -- synopsys translate_on
        port map (AD3=>ae_setcount_3, AD2=>rcount_3, AD1=>w_gcount_r23, 
            AD0=>rptr_3, DO0=>ae_set_cmp_clr);

    LUT4_1: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x4c32")
        -- synopsys translate_on
        port map (AD3=>af_setcount_3, AD2=>wcount_3, AD1=>r_gcount_w23, 
            AD0=>wptr_3, DO0=>af_set_cmp_set);

    LUT4_0: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8001")
        -- synopsys translate_on
        port map (AD3=>af_setcount_3, AD2=>wcount_3, AD1=>r_gcount_w23, 
            AD0=>wptr_3, DO0=>af_set_cmp_clr);

    FF_69: FD1P3BX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iwcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>wcount_0);

    FF_68: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iwcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_1);

    FF_67: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iwcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_2);

    FF_66: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iwcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_3);

    FF_65: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gdata_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_0);

    FF_64: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gdata_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_1);

    FF_63: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gdata_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_2);

    FF_62: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>wcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_3);

    FF_61: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>wcount_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_0);

    FF_60: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>wcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_1);

    FF_59: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>wcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_2);

    FF_58: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>wcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_3);

    FF_57: FD1P3BX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>ircount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>rcount_0);

    FF_56: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>ircount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_1);

    FF_55: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>ircount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_2);

    FF_54: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>ircount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_3);

    FF_53: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gdata_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_0);

    FF_52: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gdata_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_1);

    FF_51: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gdata_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_2);

    FF_50: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rcount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_3);

    FF_49: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rcount_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_0);

    FF_48: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rcount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_1);

    FF_47: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rcount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_2);

    FF_46: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rcount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_3);

    FF_45: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(0));

    FF_44: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(1));

    FF_43: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(2));

    FF_42: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(3));

    FF_41: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(4));

    FF_40: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(5));

    FF_39: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(6));

    FF_38: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(7));

    FF_37: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(8));

    FF_36: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(9));

    FF_35: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(10));

    FF_34: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(11));

    FF_33: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout12, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(12));

    FF_32: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout13, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(13));

    FF_31: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout14, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(14));

    FF_30: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout15, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(15));

    FF_29: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout16, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(16));

    FF_28: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>rdataout17, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>Q(17));

    FF_27: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gcount_0, CK=>RdClock, CD=>Reset, Q=>w_gcount_r0);

    FF_26: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gcount_1, CK=>RdClock, CD=>Reset, Q=>w_gcount_r1);

    FF_25: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gcount_2, CK=>RdClock, CD=>Reset, Q=>w_gcount_r2);

    FF_24: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gcount_3, CK=>RdClock, CD=>Reset, Q=>w_gcount_r3);

    FF_23: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gcount_0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w0);

    FF_22: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gcount_1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w1);

    FF_21: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gcount_2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w2);

    FF_20: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gcount_3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w3);

    FF_19: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gcount_r0, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r20);

    FF_18: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gcount_r1, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r21);

    FF_17: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gcount_r2, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r22);

    FF_16: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>w_gcount_r3, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r23);

    FF_15: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gcount_w0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w20);

    FF_14: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gcount_w1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w21);

    FF_13: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gcount_w2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w22);

    FF_12: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>r_gcount_w3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w23);

    FF_11: FD1S3BX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>empty_d, CK=>RdClock, PD=>rRst, Q=>empty_i);

    FF_10: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>full_d, CK=>WrClock, CD=>Reset, Q=>full_i);

    FF_9: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iae_setcount_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_0);

    FF_8: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iae_setcount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_1);

    FF_7: FD1P3BX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iae_setcount_2, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_setcount_2);

    FF_6: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iae_setcount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_3);

    FF_5: FD1S3BX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>ae_set_d, CK=>RdClock, PD=>rRst, Q=>AlmostEmpty);

    FF_4: FD1P3BX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iaf_setcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_setcount_0);

    FF_3: FD1P3BX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iaf_setcount_1, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_setcount_1);

    FF_2: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iaf_setcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_2);

    FF_1: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>iaf_setcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_3);

    FF_0: FD1S3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>af_set, CK=>WrClock, CD=>Reset, Q=>AlmostFull);

    w_gctr_0: CU2
        port map (CI=>scuba_vhi, PC1=>wcount_1, PC0=>wcount_0, CO=>co0, 
            NC1=>iwcount_1, NC0=>iwcount_0);

    w_gctr_1: CU2
        port map (CI=>co0, PC1=>wcount_3, PC0=>wcount_2, CO=>co1, 
            NC1=>iwcount_3, NC0=>iwcount_2);

    r_gctr_0: CU2
        port map (CI=>scuba_vhi, PC1=>rcount_1, PC0=>rcount_0, CO=>co0_1, 
            NC1=>ircount_1, NC0=>ircount_0);

    r_gctr_1: CU2
        port map (CI=>co0_1, PC1=>rcount_3, PC0=>rcount_2, CO=>co1_1, 
            NC1=>ircount_3, NC0=>ircount_2);

    empty_cmp_0: AGEB2
        port map (A1=>rcount_1, A0=>rcount_0, B1=>wcount_r1, 
            B0=>w_g2b_xor_cluster_0, CI=>rden_i, GE=>co0_2);

    empty_cmp_1: AGEB2
        port map (A1=>empty_cmp_set, A0=>rcount_2, B1=>empty_cmp_clr, 
            B0=>wcount_r2, CI=>co0_2, GE=>empty_d_c);

    a0: FADD2
        port map (A1=>scuba_vlo, A0=>scuba_vlo, B1=>scuba_vlo, 
            B0=>scuba_vlo, CI=>empty_d_c, COUT1=>open, COUT0=>open, 
            S1=>open, S0=>empty_d);

    full_cmp_0: AGEB2
        port map (A1=>wcount_1, A0=>wcount_0, B1=>rcount_w1, 
            B0=>r_g2b_xor_cluster_0, CI=>wren_i, GE=>co0_3);

    full_cmp_1: AGEB2
        port map (A1=>full_cmp_set, A0=>wcount_2, B1=>full_cmp_clr, 
            B0=>rcount_w2, CI=>co0_3, GE=>full_d_c);

    a1: FADD2
        port map (A1=>scuba_vlo, A0=>scuba_vlo, B1=>scuba_vlo, 
            B0=>scuba_vlo, CI=>full_d_c, COUT1=>open, COUT0=>open, 
            S1=>open, S0=>full_d);

    ae_set_ctr_0: CU2
        port map (CI=>scuba_vhi, PC1=>ae_setcount_1, PC0=>ae_setcount_0, 
            CO=>co0_4, NC1=>iae_setcount_1, NC0=>iae_setcount_0);

    ae_set_ctr_1: CU2
        port map (CI=>co0_4, PC1=>ae_setcount_3, PC0=>ae_setcount_2, 
            CO=>co1_2, NC1=>iae_setcount_3, NC0=>iae_setcount_2);

    ae_set_cmp_0: AGEB2
        port map (A1=>ae_setcount_1, A0=>ae_setcount_0, B1=>wcount_r1, 
            B0=>w_g2b_xor_cluster_0, CI=>rden_i, GE=>co0_5);

    ae_set_cmp_1: AGEB2
        port map (A1=>ae_set_cmp_set, A0=>ae_setcount_2, 
            B1=>ae_set_cmp_clr, B0=>wcount_r2, CI=>co0_5, GE=>ae_set_d_c);

    a2: FADD2
        port map (A1=>scuba_vlo, A0=>scuba_vlo, B1=>scuba_vlo, 
            B0=>scuba_vlo, CI=>ae_set_d_c, COUT1=>open, COUT0=>open, 
            S1=>open, S0=>ae_set_d);

    af_set_ctr_0: CU2
        port map (CI=>scuba_vhi, PC1=>af_setcount_1, PC0=>af_setcount_0, 
            CO=>co0_6, NC1=>iaf_setcount_1, NC0=>iaf_setcount_0);

    af_set_ctr_1: CU2
        port map (CI=>co0_6, PC1=>af_setcount_3, PC0=>af_setcount_2, 
            CO=>co1_3, NC1=>iaf_setcount_3, NC0=>iaf_setcount_2);

    af_set_cmp_0: AGEB2
        port map (A1=>af_setcount_1, A0=>af_setcount_0, B1=>rcount_w1, 
            B0=>r_g2b_xor_cluster_0, CI=>wren_i, GE=>co0_7);

    af_set_cmp_1: AGEB2
        port map (A1=>af_set_cmp_set, A0=>af_setcount_2, 
            B1=>af_set_cmp_clr, B0=>rcount_w2, CI=>co0_7, GE=>af_set_c);

    a3: FADD2
        port map (A1=>scuba_vlo, A0=>scuba_vlo, B1=>scuba_vlo, 
            B0=>scuba_vlo, CI=>af_set_c, COUT1=>open, COUT0=>open, 
            S1=>open, S0=>af_set);

    fifo_pfu_0_0: DPR16X2
        -- synopsys translate_off
        generic map (GSR=> "ENABLED", initval=> "0x0000000000000000")
        -- synopsys translate_on
        port map (DI0=>Data(16), DI1=>Data(17), WAD3=>scuba_vlo, 
            WAD2=>wptr_2, WAD1=>wptr_1, WAD0=>wptr_0, WRE=>scuba_vhi, 
            WPE=>wren_i, WCK=>WrClock, RAD3=>scuba_vlo, RAD2=>rptr_2, 
            RAD1=>rptr_1, RAD0=>rptr_0, WDO0=>open, WDO1=>open, 
            RDO0=>rdataout16, RDO1=>rdataout17);

    fifo_pfu_0_1: DPR16X2
        -- synopsys translate_off
        generic map (GSR=> "ENABLED", initval=> "0x0000000000000000")
        -- synopsys translate_on
        port map (DI0=>Data(14), DI1=>Data(15), WAD3=>scuba_vlo, 
            WAD2=>wptr_2, WAD1=>wptr_1, WAD0=>wptr_0, WRE=>scuba_vhi, 
            WPE=>wren_i, WCK=>WrClock, RAD3=>scuba_vlo, RAD2=>rptr_2, 
            RAD1=>rptr_1, RAD0=>rptr_0, WDO0=>open, WDO1=>open, 
            RDO0=>rdataout14, RDO1=>rdataout15);

    fifo_pfu_0_2: DPR16X2
        -- synopsys translate_off
        generic map (GSR=> "ENABLED", initval=> "0x0000000000000000")
        -- synopsys translate_on
        port map (DI0=>Data(12), DI1=>Data(13), WAD3=>scuba_vlo, 
            WAD2=>wptr_2, WAD1=>wptr_1, WAD0=>wptr_0, WRE=>scuba_vhi, 
            WPE=>wren_i, WCK=>WrClock, RAD3=>scuba_vlo, RAD2=>rptr_2, 
            RAD1=>rptr_1, RAD0=>rptr_0, WDO0=>open, WDO1=>open, 
            RDO0=>rdataout12, RDO1=>rdataout13);

    fifo_pfu_0_3: DPR16X2
        -- synopsys translate_off
        generic map (GSR=> "ENABLED", initval=> "0x0000000000000000")
        -- synopsys translate_on
        port map (DI0=>Data(10), DI1=>Data(11), WAD3=>scuba_vlo, 
            WAD2=>wptr_2, WAD1=>wptr_1, WAD0=>wptr_0, WRE=>scuba_vhi, 
            WPE=>wren_i, WCK=>WrClock, RAD3=>scuba_vlo, RAD2=>rptr_2, 
            RAD1=>rptr_1, RAD0=>rptr_0, WDO0=>open, WDO1=>open, 
            RDO0=>rdataout10, RDO1=>rdataout11);

    fifo_pfu_0_4: DPR16X2
        -- synopsys translate_off
        generic map (GSR=> "ENABLED", initval=> "0x0000000000000000")
        -- synopsys translate_on
        port map (DI0=>Data(8), DI1=>Data(9), WAD3=>scuba_vlo, 
            WAD2=>wptr_2, WAD1=>wptr_1, WAD0=>wptr_0, WRE=>scuba_vhi, 
            WPE=>wren_i, WCK=>WrClock, RAD3=>scuba_vlo, RAD2=>rptr_2, 
            RAD1=>rptr_1, RAD0=>rptr_0, WDO0=>open, WDO1=>open, 
            RDO0=>rdataout8, RDO1=>rdataout9);

    fifo_pfu_0_5: DPR16X2
        -- synopsys translate_off
        generic map (GSR=> "ENABLED", initval=> "0x0000000000000000")
        -- synopsys translate_on
        port map (DI0=>Data(6), DI1=>Data(7), WAD3=>scuba_vlo, 
            WAD2=>wptr_2, WAD1=>wptr_1, WAD0=>wptr_0, WRE=>scuba_vhi, 
            WPE=>wren_i, WCK=>WrClock, RAD3=>scuba_vlo, RAD2=>rptr_2, 
            RAD1=>rptr_1, RAD0=>rptr_0, WDO0=>open, WDO1=>open, 
            RDO0=>rdataout6, RDO1=>rdataout7);

    fifo_pfu_0_6: DPR16X2
        -- synopsys translate_off
        generic map (GSR=> "ENABLED", initval=> "0x0000000000000000")
        -- synopsys translate_on
        port map (DI0=>Data(4), DI1=>Data(5), WAD3=>scuba_vlo, 
            WAD2=>wptr_2, WAD1=>wptr_1, WAD0=>wptr_0, WRE=>scuba_vhi, 
            WPE=>wren_i, WCK=>WrClock, RAD3=>scuba_vlo, RAD2=>rptr_2, 
            RAD1=>rptr_1, RAD0=>rptr_0, WDO0=>open, WDO1=>open, 
            RDO0=>rdataout4, RDO1=>rdataout5);

    fifo_pfu_0_7: DPR16X2
        -- synopsys translate_off
        generic map (GSR=> "ENABLED", initval=> "0x0000000000000000")
        -- synopsys translate_on
        port map (DI0=>Data(2), DI1=>Data(3), WAD3=>scuba_vlo, 
            WAD2=>wptr_2, WAD1=>wptr_1, WAD0=>wptr_0, WRE=>scuba_vhi, 
            WPE=>wren_i, WCK=>WrClock, RAD3=>scuba_vlo, RAD2=>rptr_2, 
            RAD1=>rptr_1, RAD0=>rptr_0, WDO0=>open, WDO1=>open, 
            RDO0=>rdataout2, RDO1=>rdataout3);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    fifo_pfu_0_8: DPR16X2
        -- synopsys translate_off
        generic map (GSR=> "ENABLED", initval=> "0x0000000000000000")
        -- synopsys translate_on
        port map (DI0=>Data(0), DI1=>Data(1), WAD3=>scuba_vlo, 
            WAD2=>wptr_2, WAD1=>wptr_1, WAD0=>wptr_0, WRE=>scuba_vhi, 
            WPE=>wren_i, WCK=>WrClock, RAD3=>scuba_vlo, RAD2=>rptr_2, 
            RAD1=>rptr_1, RAD0=>rptr_0, WDO0=>open, WDO1=>open, 
            RDO0=>rdataout0, RDO1=>rdataout1);

    Empty <= empty_i;
    Full <= full_i;
end Structure;

-- synopsys translate_off
library SCM;
configuration Structure_CON of flexi_PCS_fifo_LUT is
    for Structure
        for all:DPR16X2 use entity SCM.DPR16X2(V); end for;
        for all:ROM16X1 use entity SCM.ROM16X1(V); end for;
        for all:AND2 use entity SCM.AND2(V); end for;
        for all:OR2 use entity SCM.OR2(V); end for;
        for all:XOR2 use entity SCM.XOR2(V); end for;
        for all:INV use entity SCM.INV(V); end for;
        for all:VHI use entity SCM.VHI(V); end for;
        for all:VLO use entity SCM.VLO(V); end for;
        for all:FADD2 use entity SCM.FADD2(V); end for;
        for all:CU2 use entity SCM.CU2(V); end for;
        for all:AGEB2 use entity SCM.AGEB2(V); end for;
        for all:FD1P3BX use entity SCM.FD1P3BX(V); end for;
        for all:FD1P3DX use entity SCM.FD1P3DX(V); end for;
        for all:FD1S3BX use entity SCM.FD1S3BX(V); end for;
        for all:FD1S3DX use entity SCM.FD1S3DX(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
