-- VHDL netlist generated by SCUBA ispLever_v70_Prod_Build (55)
-- Module  Version: 4.2
--/opt/lattice/isplever7.0/isptools/ispfpga/bin/lin/scuba -w -n flexi_PCS_fifo_EBR -lang vhdl -synth synplify -bus_exp 7 -bb -arch or5s00 -type ebfifo -depth 512 -width 18 -rwidth 18 -no_enable -pe 10 -pf 508 -e 

-- Tue Nov 27 10:58:36 2007

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library SCM;
use SCM.COMPONENTS.all;
-- synopsys translate_on

entity flexi_PCS_fifo_EBR is
    port (
        Data: in  std_logic_vector(17 downto 0); 
        WrClock: in  std_logic; 
        RdClock: in  std_logic; 
        WrEn: in  std_logic; 
        RdEn: in  std_logic; 
        Reset: in  std_logic; 
        RPReset: in  std_logic; 
        Q: out  std_logic_vector(17 downto 0); 
        Empty: out  std_logic; 
        Full: out  std_logic; 
        AlmostEmpty: out  std_logic; 
        AlmostFull: out  std_logic);
end flexi_PCS_fifo_EBR;

architecture Structure of flexi_PCS_fifo_EBR is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal Empty_int: std_logic;
    signal Full_int: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component FIFO16KA
    -- synopsys translate_off
        generic (FULLPOINTER1 : in std_logic_vector(14 downto 0); 
                FULLPOINTER : in std_logic_vector(14 downto 0); 
                AFPOINTER1 : in std_logic_vector(14 downto 0); 
                AEPOINTER1 : in std_logic_vector(14 downto 0); 
                AFPOINTER : in std_logic_vector(14 downto 0); 
                AEPOINTER : in std_logic_vector(14 downto 0); 
                CSDECODE_R : in std_logic_vector(1 downto 0); 
                CSDECODE_W : in std_logic_vector(1 downto 0); 
                RESETMODE : in String; REGMODE : in String; 
                DATA_WIDTH_R : in Integer; DATA_WIDTH_W : in Integer);
    -- synopsys translate_on
        port (DI0: in  std_logic; DI1: in  std_logic; DI2: in  std_logic; 
            DI3: in  std_logic; DI4: in  std_logic; DI5: in  std_logic; 
            DI6: in  std_logic; DI7: in  std_logic; DI8: in  std_logic; 
            DI9: in  std_logic; DI10: in  std_logic; DI11: in  std_logic; 
            DI12: in  std_logic; DI13: in  std_logic; 
            DI14: in  std_logic; DI15: in  std_logic; 
            DI16: in  std_logic; DI17: in  std_logic; 
            DI18: in  std_logic; DI19: in  std_logic; 
            DI20: in  std_logic; DI21: in  std_logic; 
            DI22: in  std_logic; DI23: in  std_logic; 
            DI24: in  std_logic; DI25: in  std_logic; 
            DI26: in  std_logic; DI27: in  std_logic; 
            DI28: in  std_logic; DI29: in  std_logic; 
            DI30: in  std_logic; DI31: in  std_logic; 
            DI32: in  std_logic; DI33: in  std_logic; 
            DI34: in  std_logic; DI35: in  std_logic; 
            FULLI: in  std_logic; CSW0: in  std_logic; 
            CSW1: in  std_logic; EMPTYI: in  std_logic; 
            CSR0: in  std_logic; CSR1: in  std_logic; WE: in  std_logic; 
            RE: in  std_logic; CLKW: in  std_logic; CLKR: in  std_logic; 
            RST: in  std_logic; RPRST: in  std_logic; 
            DO0: out  std_logic; DO1: out  std_logic; 
            DO2: out  std_logic; DO3: out  std_logic; 
            DO4: out  std_logic; DO5: out  std_logic; 
            DO6: out  std_logic; DO7: out  std_logic; 
            DO8: out  std_logic; DO9: out  std_logic; 
            DO10: out  std_logic; DO11: out  std_logic; 
            DO12: out  std_logic; DO13: out  std_logic; 
            DO14: out  std_logic; DO15: out  std_logic; 
            DO16: out  std_logic; DO17: out  std_logic; 
            DO18: out  std_logic; DO19: out  std_logic; 
            DO20: out  std_logic; DO21: out  std_logic; 
            DO22: out  std_logic; DO23: out  std_logic; 
            DO24: out  std_logic; DO25: out  std_logic; 
            DO26: out  std_logic; DO27: out  std_logic; 
            DO28: out  std_logic; DO29: out  std_logic; 
            DO30: out  std_logic; DO31: out  std_logic; 
            DO32: out  std_logic; DO33: out  std_logic; 
            DO34: out  std_logic; DO35: out  std_logic; 
            EF: out  std_logic; AEF: out  std_logic; AFF: out  std_logic; 
            FF: out  std_logic);
    end component;
    attribute FULLPOINTER1 : string; 
    attribute FULLPOINTER : string; 
    attribute AFPOINTER1 : string; 
    attribute AFPOINTER : string; 
    attribute AEPOINTER1 : string; 
    attribute AEPOINTER : string; 
    attribute RESETMODE : string; 
    attribute REGMODE : string; 
    attribute CSDECODE_R : string; 
    attribute CSDECODE_W : string; 
    attribute DATA_WIDTH_R : string; 
    attribute DATA_WIDTH_W : string; 
    attribute FULLPOINTER1 of flexi_PCS_fifo_EBR_0_0 : label is "0b011111111000001";
    attribute FULLPOINTER of flexi_PCS_fifo_EBR_0_0 : label is "0b011111111100001";
    attribute AFPOINTER1 of flexi_PCS_fifo_EBR_0_0 : label is "0b011111101000001";
    attribute AFPOINTER of flexi_PCS_fifo_EBR_0_0 : label is "0b011111101100001";
    attribute AEPOINTER1 of flexi_PCS_fifo_EBR_0_0 : label is "0b000000101111111";
    attribute AEPOINTER of flexi_PCS_fifo_EBR_0_0 : label is "0b000000101011111";
    attribute RESETMODE of flexi_PCS_fifo_EBR_0_0 : label is "ASYNC";
    attribute REGMODE of flexi_PCS_fifo_EBR_0_0 : label is "NOREG";
    attribute CSDECODE_R of flexi_PCS_fifo_EBR_0_0 : label is "0b11";
    attribute CSDECODE_W of flexi_PCS_fifo_EBR_0_0 : label is "0b11";
    attribute DATA_WIDTH_R of flexi_PCS_fifo_EBR_0_0 : label is "36";
    attribute DATA_WIDTH_W of flexi_PCS_fifo_EBR_0_0 : label is "36";
    attribute syn_keep : boolean;

begin
    -- component instantiation statements
    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    flexi_PCS_fifo_EBR_0_0: FIFO16KA
        -- synopsys translate_off
        generic map (FULLPOINTER1=> "011111111000001", FULLPOINTER=> "011111111100001", 
        AFPOINTER1=> "011111101000001", AFPOINTER=> "011111101100001", 
        AEPOINTER1=> "000000101111111", AEPOINTER=> "000000101011111", 
        RESETMODE=> "ASYNC", REGMODE=> "NOREG", CSDECODE_R=> "11", 
        CSDECODE_W=> "11", DATA_WIDTH_R=>  36, DATA_WIDTH_W=>  36)
        -- synopsys translate_on
        port map (DI0=>Data(0), DI1=>Data(1), DI2=>Data(2), DI3=>Data(3), 
            DI4=>Data(4), DI5=>Data(5), DI6=>Data(6), DI7=>Data(7), 
            DI8=>Data(8), DI9=>Data(9), DI10=>Data(10), DI11=>Data(11), 
            DI12=>Data(12), DI13=>Data(13), DI14=>Data(14), 
            DI15=>Data(15), DI16=>Data(16), DI17=>Data(17), 
            DI18=>scuba_vlo, DI19=>scuba_vlo, DI20=>scuba_vlo, 
            DI21=>scuba_vlo, DI22=>scuba_vlo, DI23=>scuba_vlo, 
            DI24=>scuba_vlo, DI25=>scuba_vlo, DI26=>scuba_vlo, 
            DI27=>scuba_vlo, DI28=>scuba_vlo, DI29=>scuba_vlo, 
            DI30=>scuba_vlo, DI31=>scuba_vlo, DI32=>scuba_vlo, 
            DI33=>scuba_vlo, DI34=>scuba_vlo, DI35=>scuba_vlo, 
            FULLI=>Full_int, CSW0=>scuba_vhi, CSW1=>scuba_vhi, 
            EMPTYI=>Empty_int, CSR0=>scuba_vhi, CSR1=>scuba_vhi, 
            WE=>WrEn, RE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, RST=>Reset, 
            RPRST=>RPReset, DO0=>open, DO1=>open, DO2=>open, DO3=>open, 
            DO4=>open, DO5=>open, DO6=>open, DO7=>open, DO8=>open, 
            DO9=>open, DO10=>open, DO11=>open, DO12=>open, DO13=>open, 
            DO14=>open, DO15=>open, DO16=>open, DO17=>open, DO18=>Q(0), 
            DO19=>Q(1), DO20=>Q(2), DO21=>Q(3), DO22=>Q(4), DO23=>Q(5), 
            DO24=>Q(6), DO25=>Q(7), DO26=>Q(8), DO27=>Q(9), DO28=>Q(10), 
            DO29=>Q(11), DO30=>Q(12), DO31=>Q(13), DO32=>Q(14), 
            DO33=>Q(15), DO34=>Q(16), DO35=>Q(17), EF=>Empty_int, 
            AEF=>AlmostEmpty, AFF=>AlmostFull, FF=>Full_int);

    Empty <= Empty_int;
    Full <= Full_int;
end Structure;

-- synopsys translate_off
library SCM;
configuration Structure_CON of flexi_PCS_fifo_EBR is
    for Structure
        for all:VHI use entity SCM.VHI(V); end for;
        for all:VLO use entity SCM.VLO(V); end for;
        for all:FIFO16KA use entity SCM.FIFO16KA(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
