-- VHDL netlist generated by SCUBA ispLever_v8.1_PROD_Build (20)
-- Module  Version: 3.5
--/d/sugar/lattice/ispLEVER8.1/isptools/ispfpga/bin/lin/scuba -w -n dll_in100_out25 -lang vhdl -synth synplify -bus_exp 7 -bb -arch ep5m00 -type dll -dll_type cid -fin 100 -clkos_div 4 -fb_mode 0 -e 

-- Thu Aug 19 13:33:44 2010

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp2m;
use ecp2m.components.all;
-- synopsys translate_on

entity dll_in100_out25 is
    port (
        clk: in  std_logic; 
        aluhold: in  std_logic; 
        clkop: out  std_logic; 
        clkos: out  std_logic; 
        lock: out  std_logic);
 attribute dont_touch : boolean;
 attribute dont_touch of dll_in100_out25 : entity is true;
end dll_in100_out25;

architecture Structure of dll_in100_out25 is

    -- internal signal declarations
    signal scuba_vlo: std_logic;
    signal clkos_t: std_logic;
    signal scuba_vhi: std_logic;
    signal clkop_t: std_logic;
    signal clk_t: std_logic;

    -- local component declarations
    component CIDDLLA
    -- synopsys translate_off
        generic (ALU_INIT_CNTVAL : in Integer; 
                ALU_UNLOCK_CNT : in Integer; ALU_LOCK_CNT : in Integer; 
                GSR : in String; CLKOS_DIV : in Integer; 
                CLKI_DIV : in Integer; CLKOS_FPHASE : in Integer; 
                CLKOS_PHASE : in Integer; CLKOP_PHASE : in Integer);
    -- synopsys translate_on
        port (CLKI: in  std_logic; CLKFB: in  std_logic; 
            RSTN: in  std_logic; ALUHOLD: in  std_logic; 
            SMIADDR9: in  std_logic; SMIADDR8: in  std_logic; 
            SMIADDR7: in  std_logic; SMIADDR6: in  std_logic; 
            SMIADDR5: in  std_logic; SMIADDR4: in  std_logic; 
            SMIADDR3: in  std_logic; SMIADDR2: in  std_logic; 
            SMIADDR1: in  std_logic; SMIADDR0: in  std_logic; 
            SMIRD: in  std_logic; SMIWR: in  std_logic; 
            SMICLK: in  std_logic; SMIWDATA: in  std_logic; 
            SMIRSTN: in  std_logic; CLKOP: out  std_logic; 
            CLKOS: out  std_logic; LOCK: out  std_logic; 
            SMIRDATA: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    attribute FREQUENCY_PIN_CLKOS : string; 
    attribute FREQUENCY_PIN_CLKOP : string; 
    attribute FREQUENCY_PIN_CLKI : string; 
    attribute GSR : string; 
    attribute CLKFB_PDEL : string; 
    attribute CLKI_PDEL : string; 
    attribute ALU_INIT_CNTVAL : string; 
    attribute ALU_UNLOCK_CNT : string; 
    attribute ALU_LOCK_CNT : string; 
    attribute CLKI_DIV : string; 
    attribute CLKOS_DIV : string; 
    attribute CLKOS_FPHASE : string; 
    attribute CLKOS_PHASE : string; 
    attribute CLKOP_PHASE : string; 
    attribute FREQUENCY_PIN_CLKOS of dll_in100_out25_0_0 : label is "25.000000";
    attribute FREQUENCY_PIN_CLKOP of dll_in100_out25_0_0 : label is "100.000000";
    attribute FREQUENCY_PIN_CLKI of dll_in100_out25_0_0 : label is "100.000000";
    attribute GSR of dll_in100_out25_0_0 : label is "DISABLED";
    attribute CLKFB_PDEL of dll_in100_out25_0_0 : label is "DEL0";
    attribute CLKI_PDEL of dll_in100_out25_0_0 : label is "DEL0";
    attribute ALU_INIT_CNTVAL of dll_in100_out25_0_0 : label is "0";
    attribute ALU_UNLOCK_CNT of dll_in100_out25_0_0 : label is "3";
    attribute ALU_LOCK_CNT of dll_in100_out25_0_0 : label is "3";
    attribute CLKI_DIV of dll_in100_out25_0_0 : label is "1";
    attribute CLKOS_DIV of dll_in100_out25_0_0 : label is "4";
    attribute CLKOS_FPHASE of dll_in100_out25_0_0 : label is "0";
    attribute CLKOS_PHASE of dll_in100_out25_0_0 : label is "270";
    attribute CLKOP_PHASE of dll_in100_out25_0_0 : label is "270";
    attribute syn_keep : boolean;
    attribute syn_noprune : boolean;
    attribute syn_noprune of Structure : architecture is true;

begin
    -- component instantiation statements
    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    dll_in100_out25_0_0: CIDDLLA
        -- synopsys translate_off
        generic map (GSR=> "DISABLED", ALU_INIT_CNTVAL=>  0, 
        ALU_UNLOCK_CNT=>  3, ALU_LOCK_CNT=>  3, CLKI_DIV=>  1, CLKOS_DIV=>  4, 
        CLKOS_FPHASE=>  0, CLKOS_PHASE=>  270, CLKOP_PHASE=>  270)
        -- synopsys translate_on
        port map (CLKI=>clk_t, CLKFB=>clkop_t, RSTN=>scuba_vhi, 
            ALUHOLD=>aluhold, SMIADDR9=>scuba_vlo, SMIADDR8=>scuba_vlo, 
            SMIADDR7=>scuba_vlo, SMIADDR6=>scuba_vlo, 
            SMIADDR5=>scuba_vlo, SMIADDR4=>scuba_vlo, 
            SMIADDR3=>scuba_vlo, SMIADDR2=>scuba_vlo, 
            SMIADDR1=>scuba_vlo, SMIADDR0=>scuba_vlo, SMIRD=>scuba_vlo, 
            SMIWR=>scuba_vlo, SMICLK=>scuba_vlo, SMIWDATA=>scuba_vlo, 
            SMIRSTN=>scuba_vlo, CLKOP=>clkop_t, CLKOS=>clkos_t, 
            LOCK=>lock, SMIRDATA=>open);

    clkos <= clkos_t;
    clkop <= clkop_t;
    clk_t <= clk;
end Structure;

-- synopsys translate_off
library ecp2m;
configuration Structure_CON of dll_in100_out25 is
    for Structure
        for all:CIDDLLA use entity ecp2m.CIDDLLA(V); end for;
        for all:VHI use entity ecp2m.VHI(V); end for;
        for all:VLO use entity ecp2m.VLO(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
