-- VHDL module instantiation generated by SCUBA Diamond_1.4_Production (87)
-- Module  Version: 4.8
-- Tue Nov 27 19:32:53 2012

-- parameterized module component declaration
component fifo_36x4k_oreg
    port (Data: in  std_logic_vector(35 downto 0); Clock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        AmFullThresh: in  std_logic_vector(11 downto 0); 
        Q: out  std_logic_vector(35 downto 0); 
        WCNT: out  std_logic_vector(12 downto 0); Empty: out  std_logic; 
        Full: out  std_logic; AlmostFull: out  std_logic);
end component;

-- parameterized module component instance
__ : fifo_36x4k_oreg
    port map (Data(35 downto 0)=>__, Clock=>__, WrEn=>__, RdEn=>__, 
        Reset=>__, AmFullThresh(11 downto 0)=>__, Q(35 downto 0)=>__, 
        WCNT(12 downto 0)=>__, Empty=>__, Full=>__, AlmostFull=>__);
