setenv SIM_WORKING_FOLDER .
set newDesign 0
if {![file exists "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/test_bench/trigger_master_tb/trigger_master_tb.adf"]} { 
	design create trigger_master_tb "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/test_bench"
  set newDesign 1
}
design open "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/test_bench/trigger_master_tb"
cd "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/test_bench"
designverincludedir -clear
designverlibrarysim -PL -clear
designverlibrarysim -L -clear
designverlibrarysim -PL pmi_work
designverlibrarysim ovi_ecp3
designverlibrarysim pcsd_work
designverdefinemacro -clear
if {$newDesign == 0} { 
  removefile -Y -D *
}
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/version.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_std.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/config.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_components.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trb3/base/trb3_components.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp2m_fifo.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/basic_type_declaration.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll.v"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll0.v"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll1.v"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll2.v"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll3.v"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll4.v"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/LA_FIFO.v"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/readoutfifo.v"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_CRC8.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/pulse_sync.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/state_sync.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram_16x8_dp.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram_dp.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram_dp_rw.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp3_fifo_16x16_dualport.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp3_fifo_18x16_dualport.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x256_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/media_interfaces/ecp3_sfp/sfp_1_125_int.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/optical_link/f_divider.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_18x1k_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trb3/base/code/input_statistics.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trb3/base/code/input_to_trigger_logic_record.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_9x2k_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/uart_trans.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/uart_rec.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trb3sc/code/debuguart.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/uart.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_ltc2600.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trb3sc/code/lcd.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trb3/base/code/sedcheck.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trb3sc/code/spi_master_generic.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trb3sc/code/load_settings.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/fpga_reboot.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/spi_dpram_32_to_8.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_databus_memory.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_slim.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_master.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_regio_bus_handler.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_flash_and_fpga_reload_record.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_regio_bus_handler_record.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trb3/base/code/trb3_tools.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/handler_ipu.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_18x2k_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_18x512_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_18x256_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x32k_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x16k_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x8k_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x4k_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x2k_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x1k_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x512_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp2m/fifo/fifo_var_oreg.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/handler_data.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/handler_trigger_and_data.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/bus_register_handler.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/signal_sync.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/pulse_stretch.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/handler_lvl1.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_sbuf6.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_19x16_obuf.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_sbuf5.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_sbuf.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_sbuf.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_priority_encoder.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_priority_arbiter.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_io_multiplexer.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_term_buf.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_onewire.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/rom_16x8.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram_16x16_dp.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_addresses.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_pattern_gen.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_regIO.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_ipudata.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_trigger.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_dummy_fifo.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_dummy_fifo.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp3_fifo_18x1k.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/trb_net16_fifo_arch.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_term.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_api_base.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_obuf_nodata.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_CRC.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_obuf.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_term_ibuf.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_ibuf.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_iobuf.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_endpoint_hades_full.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_endpoint_hades_full_handler_record.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp3_fifo_16bit_dualport.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/trb_net_fifo_16bit_bram_dualport.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/media_interfaces/ecp3_sfp/sfp_1_200_int.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/media_interfaces/trb_net16_lsm_sfp.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/media_interfaces/trb_net16_med_ecp3_sfp.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/pll_in200_out100.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/trb_net_reset_handler.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/trb3_periph_blank.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/trigger_master.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/trigger_master_tb.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/SignalDelay.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/SignalDelay_tb.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/SignalStretch.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/trigger_OR_enabled.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/trigger_master_top.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/SignalStretch_tb.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/signal_gated.vhd"
addfile "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/signal_gated_tb.vhd"
vlib "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/test_bench/trigger_master_tb/work"
set worklib work
adel -all
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/version.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_std.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/config.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_components.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trb3/base/trb3_components.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp2m_fifo.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/basic_type_declaration.vhd"
vlog -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll.v"
vlog -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll0.v"
vlog -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll1.v"
vlog -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll2.v"
vlog -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll3.v"
vlog -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/Cpll4.v"
vlog -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/LA_FIFO.v"
vlog -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/readoutfifo.v"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_CRC8.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/pulse_sync.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/state_sync.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram_16x8_dp.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram_dp.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram_dp_rw.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp3_fifo_16x16_dualport.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp3_fifo_18x16_dualport.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x256_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/media_interfaces/ecp3_sfp/sfp_1_125_int.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/optical_link/f_divider.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_18x1k_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trb3/base/code/input_statistics.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trb3/base/code/input_to_trigger_logic_record.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_9x2k_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/uart_trans.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/uart_rec.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trb3sc/code/debuguart.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/uart.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_ltc2600.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trb3sc/code/lcd.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trb3/base/code/sedcheck.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trb3sc/code/spi_master_generic.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trb3sc/code/load_settings.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/fpga_reboot.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/spi_dpram_32_to_8.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_databus_memory.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_slim.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_master.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_regio_bus_handler.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/spi_flash_and_fpga_reload_record.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_regio_bus_handler_record.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trb3/base/code/trb3_tools.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/handler_ipu.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_18x2k_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_18x512_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_18x256_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x32k_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x16k_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x8k_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x4k_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x2k_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x1k_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_36x512_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp2m/fifo/fifo_var_oreg.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/handler_data.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/handler_trigger_and_data.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/bus_register_handler.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/signal_sync.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/pulse_stretch.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/handler_lvl1.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_sbuf6.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/fifo/fifo_19x16_obuf.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_sbuf5.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_sbuf.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_sbuf.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_priority_encoder.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_priority_arbiter.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_io_multiplexer.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_term_buf.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_onewire.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/rom_16x8.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/basics/ram_16x16_dp.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_addresses.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_pattern_gen.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_regIO.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_ipudata.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_trigger.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_dummy_fifo.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_dummy_fifo.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp3_fifo_18x1k.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/trb_net16_fifo_arch.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_term.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_api_base.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_obuf_nodata.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net_CRC.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_obuf.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_term_ibuf.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_ibuf.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_iobuf.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_endpoint_hades_full.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/trb_net16_endpoint_hades_full_handler_record.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/lattice_ecp3_fifo_16bit_dualport.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/lattice/ecp3/trb_net_fifo_16bit_bram_dualport.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/media_interfaces/ecp3_sfp/sfp_1_200_int.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/media_interfaces/trb_net16_lsm_sfp.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/media_interfaces/trb_net16_med_ecp3_sfp.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/workdir/pll_in200_out100.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trbnet/special/trb_net_reset_handler.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/trb3_periph_blank.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/trigger_master.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/trigger_master_tb.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/SignalDelay.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/SignalDelay_tb.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/SignalStretch.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/trigger_OR_enabled.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/trigger_master_top.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/SignalStretch_tb.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/signal_gated.vhd"
vcom -dbg -work work "E:/FPGA/trigger_FPGA_MUSE/trig_MUSE_Master/Source/signal_gated_tb.vhd"
entity tb_trigger_master
vsim  +access +r tb_trigger_master   -PL pmi_work -L ovi_ecp3 -L pcsd_work
add wave *
run 1000ns
