

// TOOL:     vlog2tf
// DATE:     Thu Feb 19 09:49:41 2015
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   Top
// DESIGN:   Top
// FILENAME: TrigTest1_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ps / 1 ps

// Define Module for Test Fixture
module ScatterTrig_tf();

// Inputs
	
    reg [63:0] INP;
    reg InpA;
    reg InpB;
    reg InpC;
	
	// Outputs
    wire [2:0] OutpA;
    wire [2:0] OutpB;
    wire [2:0] OutpC;

	reg clk;
// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    ScatterTrig UUT (
		.CLK_PCLK_RIGHT(clk),
        .INP(INP), 
        .InpA(InpA), 
        .InpB(InpB), 
        .InpC(InpC),
        .OutpA(OutpA), 
        .OutpB(OutpB), 
        .OutpC(OutpC)
        );

	// define clock
	initial clk = 0;
        always #2500 
        	begin
        		clk = ~clk;
        	end
			
			
// Initialize Inputs
// You can add your stimulus here
    initial begin
            INP = 0;
            InpA = 1;
            InpB = 0;
            InpC = 0;
			
			#1000 INP=64'h0000000000000000;	
			/*#10000 INP[0]=1'b 1;
                   INP[4]=1'b 1;
                   INP[7]=1'b 1;
                   INP[15]=1'b 1;    
			#10000 INP[0]=1'b 0;
                   INP[4]=1'b 0;
                   INP[7]=1'b 0;
                   INP[15]=1'b 0;    
			#10000 INP[0]=1'b 1;
			#10000 INP[0]=1'b 0;
			#10000 INP[1]=1'b 1;
			#10000 INP[1]=1'b 0;
			#5000 INP[2]=1'b 1;
			#5000 INP[2]=1'b 0;
			#5000 INP[2]=1'b 1;
			#1000 INP[2]=1'b 0;
			#10000 INP[0]=1'b 1;
			#10000 INP[1]=1'b 1;
			#3500 INP[2]=1'b 1;
			#10000 INP[1]=1'b 0;
			       INP[0]=1'b 0;
			#5000 INP[2]=1'b 0;
			#55000 INP[5]=1'b 1;				
			#5000 INP[5]=1'b 0;*/
			
			#5000 INP[0] = 1'b1;
			 INP[1] = 1'b1;
			 INP[2] = 1'b1;
			 INP[3] = 1'b1;
			 INP[4] = 1'b1;
			 INP[5] = 1'b1;
			
			//#50000 INP[5] = 1'b0;
			//#70000 INP[5] = 1'b1;

			 INP[18] = 1'b1;
			 INP[19] = 1'b1;
			 INP[20] = 1'b1;
			 INP[21] = 1'b1;
			 INP[22] = 1'b1;
			 INP[23] = 1'b1;
		  
		  #50000 INP[0] = 1'b0;
			 INP[1] = 1'b0;
			 INP[2] = 1'b0;
			 INP[3] = 1'b0;
			 INP[4] = 1'b0;
			 INP[5] = 1'b0;
			
			//#50000 INP[5] = 1'b0;
			//#70000 INP[5] = 1'b1;

			 INP[18] = 1'b0;
			 INP[19] = 1'b0;
			 INP[20] = 1'b0;
			 INP[21] = 1'b0;
			 INP[22] = 1'b0;
			 INP[23] = 1'b0;
			 
		#10000 INP[0] = 1'b1;
			 INP[1] = 1'b1;
			 INP[2] = 1'b1;
			 INP[3] = 1'b1;
			 INP[4] = 1'b1;
			 INP[5] = 1'b1;
			
			//#50000 INP[5] = 1'b0;
			//#70000 INP[5] = 1'b1;

			 INP[18] = 1'b1;
			 INP[19] = 1'b1;
			 INP[20] = 1'b1;
			 INP[21] = 1'b1;
			 INP[22] = 1'b1;
			 INP[23] = 1'b1;
		  
		  #50000 INP[0] = 1'b0;
			 INP[1] = 1'b0;
			 INP[2] = 1'b0;
			 INP[3] = 1'b0;
			 INP[4] = 1'b0;
			 INP[5] = 1'b0;
			
			//#50000 INP[5] = 1'b0;
			//#70000 INP[5] = 1'b1;

			 INP[18] = 1'b0;
			 INP[19] = 1'b0;
			 INP[20] = 1'b0;
			 INP[21] = 1'b0;
			 INP[22] = 1'b0;
			 INP[23] = 1'b0;
			 
		 #10000 INP[1] = 1'b1;
			 INP[2] = 1'b1;
			 INP[3] = 1'b1;
			 INP[4] = 1'b1;
			 INP[5] = 1'b1;
			 INP[6] = 1'b1;
			
			//#50000 INP[5] = 1'b0;
			//#70000 INP[5] = 1'b1;

			 INP[18] = 1'b1;
			 INP[19] = 1'b1;
			 INP[20] = 1'b1;
			 INP[21] = 1'b1;
			 INP[22] = 1'b1;
			 INP[23] = 1'b1;
		  
		  #50000 INP[1] = 1'b0;
			 INP[2] = 1'b0;
			 INP[3] = 1'b0;
			 INP[4] = 1'b0;
			 INP[5] = 1'b0;
			 INP[6] = 1'b0;
			
			//#50000 INP[5] = 1'b0;
			//#70000 INP[5] = 1'b1;

			 INP[18] = 1'b0;
			 INP[19] = 1'b0;
			 INP[20] = 1'b0;
			 INP[21] = 1'b0;
			 INP[22] = 1'b0;
			 INP[23] = 1'b0;
			 	 
			 
			
			#50000 INP[35] = 1'b1;
			#60000 INP[36] = 1'b1;
			#70000 INP[37] = 1'b1;


    end

endmodule // ScatterTrig_tf