-- VHDL module instantiation generated by SCUBA ispLever_v71_PROD_Build (58)
-- Module  Version: 4.0
-- Wed Jul 23 11:49:33 2008

-- parameterized module component declaration
component lattice_scm_clock_300
    generic (SMI_OFFSET : in String := "0x410"
    );
    port (clk: in  std_logic; clkop: out  std_logic; 
        clkos: out  std_logic; lock: out  std_logic);
end component;

-- parameterized module component instance
__ : lattice_scm_clock_300
    generic map ( SMI_OFFSET=>____)
    port map (clk=>__, clkop=>__, clkos=>__, lock=>__);
