/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.1.502 */
/* Module Version: 5.7 */
/* Thu Aug 11 09:50:47 2016 */

/* parameterized module instance */
mypll1 __ (.CLK( ), .RSTK( ), .FINEDELB0( ), .FINEDELB1( ), 
    .FINEDELB2( ), .FINEDELB3( ), .DPHASE0( ), .DPHASE1( ), .DPHASE2( ), 
    .DPHASE3( ), .CLKOP( ), .CLKOS( ), .CLKOK( ), .LOCK( ));
