--  This is SPS trigger code for signal generated by ANDing (one front bar) with (the OR of--- adjacent five back bars).
---- //////////////////////////////// Written by Shraddha Dogra.///////////////////////////


library  ieee;
use  ieee.std_logic_1164.all;

library work;
use work.trb_net_std.all;

entity Scat_LUT5 is
port(
     in_clk: in std_logic;
	  in_front_bars: in std_logic_vector (17 downto 0);
	  in_back_bars: in std_logic_vector (45 downto 18);
	  out_scat_LUT5: out std_logic);
end scat_LUT5;

architecture structural of Scat_LUT5 is
 signal and_temp : std_logic_vector(17 downto 0);
 signal andedout: std_logic_vector(17 downto 0);
	
 
 component BackOr5 is 
    port(
	back: in std_logic_vector (27 downto 0);
    and_out: out std_logic_vector  (17 downto 0));  
 end component BackOr5;
 
 component Or18 is
      port( input1: in std_logic_vector(17 downto 0);
            output1: out std_logic);  
 end component Or18;

 begin
	
 Backor: BackOr5
	          port map(
			           back => in_back_bars,
					   and_out => and_temp);
 anded_out:				   
	 for i in 0 to 17 generate
	 andedout(i) <= in_front_bars(i) and and_temp(i);
     end generate anded_out;
 
 Gen_Or: Or18
          port map(
		           input1 => andedout,
				   output1 => out_scat_LUT5);
  
end structural;




